/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as FeasibilityRouteImport } from './routes/feasibility'
import { Route as ImpactsRouteImport } from './routes/impacts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SolutionRouteImport } from './routes/solution'
import { Route as TechnicalRouteImport } from './routes/technical'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const FeasibilityRoute = FeasibilityRouteImport.update({
  id: '/feasibility',
  path: '/feasibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactsRoute = ImpactsRouteImport.update({
  id: '/impacts',
  path: '/impacts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionRoute = SolutionRouteImport.update({
  id: '/solution',
  path: '/solution',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalRoute = TechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRoute
  '/feasibility': typeof FeasibilityRoute
  '/impacts': typeof ImpactsRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRoute
  '/problems': typeof ProblemsRoute
  '/research': typeof ResearchRoute
  '/solution': typeof SolutionRoute
  '/technical': typeof TechnicalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRoute
  '/feasibility': typeof FeasibilityRoute
  '/impacts': typeof ImpactsRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRoute
  '/problems': typeof ProblemsRoute
  '/research': typeof ResearchRoute
  '/solution': typeof SolutionRoute
  '/technical': typeof TechnicalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRoute
  '/feasibility': typeof FeasibilityRoute
  '/impacts': typeof ImpactsRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRoute
  '/problems': typeof ProblemsRoute
  '/research': typeof ResearchRoute
  '/solution': typeof SolutionRoute
  '/technical': typeof TechnicalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doctor'
    | '/feasibility'
    | '/impacts'
    | '/login'
    | '/patient'
    | '/problems'
    | '/research'
    | '/solution'
    | '/technical'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/doctor'
    | '/feasibility'
    | '/impacts'
    | '/login'
    | '/patient'
    | '/problems'
    | '/research'
    | '/solution'
    | '/technical'
  id:
    | '__root__'
    | '/'
    | '/doctor'
    | '/feasibility'
    | '/impacts'
    | '/login'
    | '/patient'
    | '/problems'
    | '/research'
    | '/solution'
    | '/technical'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorRoute: typeof DoctorRoute
  FeasibilityRoute: typeof FeasibilityRoute
  ImpactsRoute: typeof ImpactsRoute
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRoute
  ProblemsRoute: typeof ProblemsRoute
  ResearchRoute: typeof ResearchRoute
  SolutionRoute: typeof SolutionRoute
  TechnicalRoute: typeof TechnicalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feasibility': {
      id: '/feasibility'
      path: '/feasibility'
      fullPath: '/feasibility'
      preLoaderRoute: typeof FeasibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impacts': {
      id: '/impacts'
      path: '/impacts'
      fullPath: '/impacts'
      preLoaderRoute: typeof ImpactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solution': {
      id: '/solution'
      path: '/solution'
      fullPath: '/solution'
      preLoaderRoute: typeof SolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical': {
      id: '/technical'
      path: '/technical'
      fullPath: '/technical'
      preLoaderRoute: typeof TechnicalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorRoute: DoctorRoute,
  FeasibilityRoute: FeasibilityRoute,
  ImpactsRoute: ImpactsRoute,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRoute,
  ProblemsRoute: ProblemsRoute,
  ResearchRoute: ResearchRoute,
  SolutionRoute: SolutionRoute,
  TechnicalRoute: TechnicalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
